// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-I_l2fzetDNmrykJIcug8ZpooesYSi-8',
    appId: '1:920413736023:web:41543f35cfb019baaa6712',
    messagingSenderId: '920413736023',
    projectId: 'agriapp-c2b55',
    authDomain: 'agriapp-c2b55.firebaseapp.com',
    databaseURL: 'https://agriapp-c2b55-default-rtdb.firebaseio.com',
    storageBucket: 'agriapp-c2b55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxl-NdcBlZy4GaMEgSqxt-rGzNvDur7zo',
    appId: '1:788094866557:android:558bc5d979769de0c4cd14',
    messagingSenderId: '788094866557',
    projectId: 'kindicare-uat',
    // databaseURL: 'https://agriapp-c2b55-default-rtdb.firebaseio.com',
    storageBucket: 'kindicare-uat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgRwRWhNTBLHl_ZiQdwFEPwFvxZvACFjM',
    appId: '1:788094866557:ios:58901dbfe3f80ed6c4cd14',
    messagingSenderId: '788094866557',
    projectId: 'kindicare-uat',
    // databaseURL: 'https://agriapp-c2b55-default-rtdb.firebaseio.com',
    storageBucket: 'kindicare-uat.appspot.com',
    iosBundleId: 'com.kindicare.app.uat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG_Juj_TPwA75SizXhJbqgwCz0B29z6Mg',
    appId: '1:920413736023:ios:3e7fc76de37a2f67aa6712',
    messagingSenderId: '920413736023',
    projectId: 'agriapp-c2b55',
    databaseURL: 'https://agriapp-c2b55-default-rtdb.firebaseio.com',
    storageBucket: 'agriapp-c2b55.appspot.com',
    iosBundleId: 'com.example.notiFcm.RunnerTests',
  );
}
